version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: dimitrius
      POSTGRES_PASSWORD: dimi
      POSTGRES_DB: sticky-notes-kiii
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: dimitrijk/sticky-notes-spring-kiii:1.2
    container_name: stickies-spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sticky-notes-kiii
      SPRING_DATASOURCE_USERNAME: dimitrius
      SPRING_DATASOURCE_PASSWORD: dimi
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
    depends_on:
      - db

volumes:
  postgres-data:

