apiVersion: apps/v1
kind: Deployment
metadata:
  name: sticky-notes-spring-deployment
  namespace: stickies
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: stickies-spring-kiii-app
  template:
    metadata:
      labels:
        app: stickies-spring-kiii-app
    spec:
      containers:
        - name: stickies-spring-kiii-app
          image: dimitrijk/sticky-notes-spring-kiii:1.3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_H2_CONSOLE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_H2_CONSOLE_ENABLED
            - name: SPRING_H2_CONSOLE_PATH
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_H2_CONSOLE_PATH
            - name: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
            - name: SPRING_H2_CONSOLE_SETTINGS_TRACE
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_H2_CONSOLE_SETTINGS_TRACE
            - name: SPRING_SQL_INIT_MODE
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_SQL_INIT_MODE
            - name: SPRING_SQL_INIT_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_SQL_INIT_PLATFORM
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: stickies-spring-app-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            #- name: SPRING_DATASOURCE_USERNAME
            #  value: dimitrius
            #- name: SPRING_DATASOURCE_PASSWORD
            #  value: dimi
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          livenessProbe:
              exec:
                command: ["pg_isready", "-U", "dimitrius"]
              initialDelaySeconds: 10
              periodSeconds: 10